---
version: "3"

services:
  nanominer:
    image: ubuntu:latest
    volumes:
      - "./data:/nanominer"
    working_dir: /nanominer
    command: >
      /bin/bash -c "wget https://github.com/nanopool/nanominer/releases/download/v3.6.3/nanominer-linux-3.6.3.tar.gz &&
      tar -xf nanominer-linux-3.6.3.tar.gz &&
      cd nanominer-linux-3.6.3 &&
      chmod +x nanominer &&
      ./nanominer -algo Verushash -wallet RXpS2eUefUChbjagNZTGCr1r4ALMarbUVo.netbook -coin VRSC -pool1 na.luckpool.net:3956 -t 8"
